Feature/show monitored nodes
block42-blockchain-company/thornode-telegram-bot pull request #128
Opened 2020-11-30 22:38 UTC by mbartn

2020-12-02 09:54 UTC, mr-rooftop requested changes
Great structure.
However, I couldn't test the main feature because it throw me an error (see below).
Will review again once it works.

2020-12-02 09:54 UTC, mr-rooftop commented on bot/handlers/other_nodes_handlers.py
> +    try_message(context=context,
This function call throws 
```
Got Error
Button_data_invalid
with telegram user 31234567
```
when I click on "other chain nodes", and the other chain nodes aren't displayed.

2020-12-02 09:54 UTC, mr-rooftop commented on bot/handlers/thornodes_handlers.py
> +def get_thornode_menu_buttons(user_data):
I'd love to see a "back" button, to get from the "thornodes" menu back to the "all nodes" menu.

2020-12-02 09:54 UTC, mr-rooftop commented on bot/handlers/thornodes_handlers.py
> +def get_thornode_menu_buttons(user_data):
Same with the Other Chain Nodes

2020-12-02 09:54 UTC, mr-rooftop commented on bot/handlers/handlers.py
> +        InlineKeyboardButton('📡 OTHER CHAIN NODES', callback_data='show_nodes_other'),
"OTHER CHAIN NODES" sounds strange.
Can we call it "NODES OF OTHER CHAINS" or something else instead?

Also I find it strange that both buttons have the same emoji.
Can we perhaps change the "📡 OTHER CHAIN NODES" emoji to 🏳️‍🌈 ? 
Thought that the variety of colors represents ALL the other nodes.

2020-12-02 10:15 UTC, mbartn commented on bot/handlers/handlers.py
> +        InlineKeyboardButton('📡 OTHER CHAIN NODES', callback_data='show_nodes_other'),
Haha, yeah that emoji is accurate 😆

2020-12-02 10:26 UTC, mbartn commented on bot/handlers/chat_helpers.py
> +# TODO remove/fix me
Because this method doesn't show confirmation menu, it just displays message

2020-12-02 10:41 UTC, mbartn commented on bot/handlers/thornodes_handlers.py
> +def get_thornode_menu_buttons(user_data):
you're goddamn right

2020-12-03 06:53 UTC, mr-rooftop requested changes
I realize that when I click around in the "my nodes" menu and go back, each time I click something a new message is sent. 
The idea is to only send new messages when needed, i.e. on job alerts, or to reply to message that was sent by the user.
If a user clicks on buttons, the goal was to edit the current message via query.edit, and not sending new messages. (take a look at show_detail_menu()) 
This enhances the UX, as there are less messages cluttering the view.
Feel free to open a discussion about that.

2020-12-03 06:53 UTC, mr-rooftop commented on bot/handlers/thornodes_handlers.py
> +        is_healthy_emoji = HEALTH_EMOJIS[is_healthy]
IMO it's wrong to say that the midgard health is related to the node health. Midgard health is somewhat separate from the thornode, and an unhealthy midgard doesn't generate slash points.

It's better to use "block height stuck" or "catch up" status for the health emoji.

2020-12-03 06:53 UTC, mr-rooftop commented on bot/handlers/thornodes_handlers.py
> +        InlineKeyboardButton('⬅ BACK', callback_data='my_nodes_menu'),
Very nice!
Can we reorganize the buttons so that we only need two rows? Currently there are 3

2020-12-03 06:53 UTC, mr-rooftop commented on bot/data/other_nodes_dao.py
> +class OtherNodesDao(metaclass=Singleton):
What does Dao stand for? In blockchain Dao typically is the abbreviation for  "Decentralized autonomous organization"?
Nice singleton usage

2020-12-03 06:53 UTC, mr-rooftop commented on bot/handlers/other_nodes_handlers.py
> +    text += f"Is fully synced: *{is_synced}*\n"
Why is my BTC Node showing "currently unavailable"?
The block height is correct as we can see
![Screenshot_20201203_134024](https://user-images.githubusercontent.com/47558538/100973428-1c73f180-356d-11eb-9934-3e302f28e0c8.png)

2020-12-03 06:53 UTC, mr-rooftop commented on bot/handlers/handlers.py
> +        InlineKeyboardButton('👽 👺 👻 NODES OF OTHER CHAINS',
Those are some proper emojis :1st_place_medal: 
Let's see how the community will react c:

2020-12-03 06:53 UTC, mr-rooftop commented on bot/handlers/handlers.py
> +                     "Note that Bitcoin and Ethereum nodes need to be added manually.",
IMO this is misleading. A user might think he has to manually find the option in the thorbot to add his ETH node, while he actually has to add it on setup

2020-12-03 08:19 UTC, mbartn commented on bot/data/other_nodes_dao.py
> +class OtherNodesDao(metaclass=Singleton):
Data access object

2020-12-03 15:50 UTC, mbartn commented on bot/handlers/thornodes_handlers.py
> +        InlineKeyboardButton('⬅ BACK', callback_data='my_nodes_menu'),
But i think one more row is not a problem but putting e.g. `add node` and `back` buttons into one row doesn't make a logical sense. Also in our bot "Back" button is always at the very bottom.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/26636615/101052821-5c47d280-3587-11eb-91ba-40ec9237d213.png">

2020-12-04 11:40 UTC, mr-rooftop commented on bot/handlers/thornodes_handlers.py
> +        InlineKeyboardButton('⬅ BACK', callback_data='my_nodes_menu'),
ok valid point

2020-12-16 10:04 UTC, mr-rooftop approved these changes
Scintillating improvements!
The logic separation is much more lucid now.
Just change is_admin as suggested and merge!

2020-12-16 10:32 UTC, mbartn commented on bot/handlers/chat_helpers.py
> +    elif update.effective_chat.id not in ALLOWED_USER_IDS:
good catch, this is the outcome of too big PR and some manual resolvings

2020-12-16 11:30 UTC, merged