Thor 10/profit roll up
block42-blockchain-company/thornode-telegram-bot pull request #147
Opened 2021-02-23 08:06 UTC by DollyVolley

## Description

This feature provides profit rollup stats in the node status message. It brings new components to the setup, like a database (mongoDB) and a binary [(tendermint client)](https://github.com/block42-blockchain-company/tendermint_block_parser).  
The tmClient parses the blockchain beginning from blockheight 1 and keeps track of churn_events and bond_rewards, which are organized in a churn_cycle state. It then populates the mongoDB with these churn_cycles. 

The telegram bot then queries the database based on the block height at the specified time (day, week, month ago and overall).

At start-up, the bot also forks the tmClient, and regularly checks on it's state (1m interval) in a dedicated job.

There are two environments for running the bot now, which can be specified with the environment variable NATIVE_DEPLOYMENT ("True" for non container run eg. development and IDE) otherwise it assumes that it is containerized.
This handles the connection to the mongoDB instance, which is always run as a container. If NATIVE_DEPLOYMENT = "True", the bot checks for an existing mongoDB container and if non-existent it creates one. 

## Fixes (issue)

None

## Improvements

None

## How Has This Been Tested?

Validation of the profit rollup in the early network (blockheight < 200k). 
This is still to be done

## Checklist:
If you have any comments regarding one of these points just write it down.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-24 07:36 UTC, mr-rooftop requested changes
With the introduction of binaries, the node operator has to trust us that these binaries are not malicious.
How can we ensure this?

I received this error when I ran the bot with faulty docker environment:
![Screenshot_20210224_142221](https://user-images.githubusercontent.com/47558538/108962815-df228a00-76ab-11eb-8931-59f6719cdd29.png)
I fixed my environment, the error doesn't happen anymore.
But it's strange that there's the path of "dollbert"
This indicates that this isn't the original binary right?

Binary handling and mongoDB protection are the major things that need to be improved imo.
The logic itself seems fine, although I didn't fully dissect the calculation logic of the profits.

2021-02-24 07:36 UTC, mr-rooftop commented on bot/service/thorchain_network_service.py
> +            #logger.info(f"In churn_cycle {churn_cycle['_churn_number']} with {churn_profit} profit and af = {accredited_factor}")
comment in or delete

2021-02-24 07:36 UTC, mr-rooftop commented on bot/service/utils.py
> +        "overall_rollup": 0
why is this 0?
Shouldn't we remove it if it's always 0?

2021-02-24 07:36 UTC, mr-rooftop commented on bot/service/utils.py
> +        return True,  progress
nice use of tuple returns, wasn't aware that that's possible :+1:

2021-02-24 07:36 UTC, mr-rooftop commented on bot/thornode_bot.py
> +    block_parser = Popen(['../binaries/tmClient'], stdout=subprocess.DEVNULL)
would rename tmClient to tendermintClient, so people understand what the binary is about when they go through the folder structure

2021-02-24 07:36 UTC, mr-rooftop commented on bot/handlers/thornodes_handlers.py
> +            text += f"_Note: Block parser is still catching up. Currently at {round(progress * 100, 1)}%_\n"
I'd make even 2 decimals. If I start my own bot, I immediately want to see that the syncing works by having 0.01%. 
I don't want to wait 1 hour until I have 0.1%

2021-02-24 07:36 UTC, mr-rooftop commented on bot/handlers/thornodes_handlers.py
> +            text += f"_Note: Block parser is still catching up. Currently at {round(progress * 100, 1)}%_\n"
oh ok, after 5 min I have already 0.1%, I guess that's fine :+1:

2021-02-24 11:29 UTC, DollyVolley commented on README.md
> +for certain data. Make sure an instance is running with the name ``thornode_bot_mongodb``, otherwise the bot can not connect.
No an instance is the mongoDB container in this context.

2021-02-24 11:31 UTC, DollyVolley commented on bot/service/utils.py
> +        "overall_rollup": 0
I use this to define the all profit rollup time-ranges of interest. 
Its 0 because in overall we want to know starting from the genesis and this format also eases computation in the returning function

2021-02-24 11:31 UTC, DollyVolley commented on bot/thornode_bot.py
> +    block_parser = Popen(['../binaries/tmClient'], stdout=subprocess.DEVNULL)
True!

2021-02-24 11:34 UTC, DollyVolley commented
Hahahaha, I have actually no clue why the name is in there. Must be included at compilation time. 
Yes it is true that loading the should be handled in a more elegant way (build from git). 

Not really sure about the mongoDB protection since it does not contain any critical data at all.

Sorry I changed quite some parts yesterday after openening the PR, since I needed to handle loading the snapshot and additional stuff.

Next commit will already contain the missing test as well. 

Thanks!

2021-02-28 03:55 UTC, mr-rooftop commented
About the mongodb protection: True, it's not critical. However, I still suggest changing at least the default port, so that automatic web crawlers that scan for the default port cannot cause any troubles.

2021-03-08 10:27 UTC, mbartn commented on bot/constants/globals.py
> +NATIVE_DEPLOYMENT = bool(os.environ['NATIVE_DEPLOYMENT'] == 'True') if 'NATIVE_DEPLOYMENT' in os.environ else False
```suggestion
NATIVE_DEPLOYMENT = bool(os.environ.get('NATIVE_DEPLOYMENT', False) == 'True')
```

2021-03-08 10:29 UTC, mbartn commented on bot/constants/globals.py
> +RUNE_TO_THOR = 100000000
what is `RUNE_TO_THOR`? Can we improve this var names readability?

2021-03-08 10:31 UTC, mbartn commented on bot/handlers/mongodb_handler.py
> +        if block_height > MONGO_SNAPSHOT_HEIGHT:
Can we just load snapshot if mongo is empty/doesnt contain proper document? Then we dont need this check

2021-03-08 10:45 UTC, mbartn commented on bot/handlers/block_parser_handler.py
> +import subprocess
`/handlers` folder is meant to contain telegram handlers, I think this is more like `service`

2021-03-08 10:45 UTC, mbartn commented on bot/handlers/block_parser_handler.py
> +import subprocess
same for mongodb_handler

2021-03-08 10:46 UTC, mbartn commented on bot/constants/globals.py
> +MONGO_URL = "localhost" if NATIVE_DEPLOYMENT else "thornode_bot_mongodb"
I would personally put here full MONGO_URI that initializes `MongoClient`, IMO it's more flexible as you can have different port in both configurations

2021-03-08 10:47 UTC, mbartn commented on bot/handlers/mongodb_handler.py
> +        if block_height > MONGO_SNAPSHOT_HEIGHT:
See [Initializing fresh instance](https://hub.docker.com/_/mongo)

2021-03-08 10:49 UTC, mbartn commented on bot/handlers/mongodb_handler.py
> +def spin_up_mongo_db():
Imo this should be done manually be developer and he should have one liner that starts local mongodb container that is used when DEBUG=True (?)

2021-03-08 10:52 UTC, mbartn commented on bot/handlers/block_parser_handler.py
> +    block_parser = Popen(['../binaries/tendermintClient'], stdout=subprocess.DEVNULL)
If we don't need to communicate with this process it could be just run as a part of the docker-compose - you would also solve the problem of having the binary

2021-03-08 16:05 UTC, DollyVolley commented on bot/constants/globals.py
> +NATIVE_DEPLOYMENT = bool(os.environ['NATIVE_DEPLOYMENT'] == 'True') if 'NATIVE_DEPLOYMENT' in os.environ else False
Damn Michal beast!

2021-03-08 16:06 UTC, DollyVolley commented on bot/constants/globals.py
> +RUNE_TO_THOR = 100000000
Yes we can!

2021-03-11 07:27 UTC, merged