Feature/us2 tasks
block42-blockchain-company/thornode-telegram-bot pull request #93
Opened 2020-09-15 21:56 UTC by mbartn

* removed `local_storage_service` for now because it was buggy, i made a mistake to initialize it with the context which should be dynamic for each call, let's use `user_data dict` inline for now
* refresh nodes in `user_data` from network on every restart
* fix #86 
* refactoring

2020-09-17 10:48 UTC, mr-rooftop requested changes

2020-09-17 10:48 UTC, mr-rooftop commented on bot/handlers/network_info.py
> +        versions_counter = Counter(map(lambda v: v['version'], active_validators))
SCOUT Bartnicki, you left the place behind clean af!

2020-09-17 10:48 UTC, mr-rooftop commented on bot/thornode_bot.py
> +                new_node = next(n for n in new_node_accounts if n['address'] == address)
On this line I get a key error
```
KeyError: 'address'
```
I think we need "node_address" instead

2020-09-22 15:19 UTC, mbartn commented on bot/thornode_bot.py
> +                new_node = next(n for n in new_node_accounts if n['address'] == address)
Good catch, no idea why i did it this way

2020-09-23 04:22 UTC, mr-rooftop approved these changes

2020-09-23 04:22 UTC, mr-rooftop commented on bot/thornode_bot.py
> +        return
When I run the testcases, here is always the excpetion thrown:
```
constants - ERROR - Fatal error! I couldn't get node accounts to update the local user_data!
.
.
ConnectionRefusedError: [Errno 111] Connection refused
```

Seems like the mock_api is not ready yet. 
Don't know why this happens only with the integration tests, and not when I run the bot normally.
I added `time.sleep(3)` after the debug process instantiation which solved the error throwing.

2020-09-23 11:54 UTC, mbartn commented on bot/thornode_bot.py
> +        return
I decided to go with `sleep()`, it's not really elegant however we want to abandon the mock api process anyway in the future

2020-09-23 11:55 UTC, merged