Kubernetes setup with README explanation
block42-blockchain-company/thornode-telegram-bot pull request #97
Opened 2020-09-20 13:00 UTC by mr-rooftop

2020-09-23 09:35 UTC, mbartn requested changes
I ran kubernetes with this docs and everything went smootly even though i don't have any experience with k8s.

I haven't check logical part of the `.yaml` files as I would need to spend a few hours for actually reading about k8s stuff. If you think that's necessary just let me know.

2020-09-23 09:35 UTC, mbartn commented on README.md
> +Now run
```suggestion
Now, from the project's main directoty, run 
```

2020-09-23 09:35 UTC, mbartn commented on README.md
> +### [Kubernetes](#kubernetes)
What's the difference between this section and 
```
### Kubernetes (K8s)
```
from line 24?

How about merging the previous section with this one?

2020-09-23 09:35 UTC, mbartn commented on README.md
> +### [Kubernetes](#kubernetes)
```suggestion
### [Kubernetes](#kubernetes)
#### Setup
```
How do you see divding the whole kubernetes section into:
- Setup
- Modyfing existing deployment (?)

More in next comments

2020-09-23 09:35 UTC, mbartn commented on README.md
> +
```suggestion
#### Modifying the running deployment (?)
```

2020-09-23 09:35 UTC, mbartn commented on README.md
> +---
```suggestion
```

2020-09-23 09:35 UTC, mbartn commented on README.md
> +---
(if you decide to divide k8s section)

2020-09-25 14:26 UTC, mr-rooftop commented on README.md
> +### [Kubernetes](#kubernetes)
The first section is part of the "quickstart" section, which aims to give minimal information to set everything up.
The latter section explains the K8s setup in more detail.
IMO it makes sense to provide the user with the easy to use "quickstart" section in addition to the lengthier detail sections.

2020-09-25 14:29 UTC, mr-rooftop commented on README.md
> +### [Kubernetes](#kubernetes)
Neat idea

2020-09-28 15:55 UTC, mbartn commented on README.md
> +### [Kubernetes](#kubernetes)
ok, so let's leave that

2020-09-29 06:06 UTC, mbartn approved these changes

2020-09-29 07:10 UTC, merged